name: wafar_cash
description: coupons, deals and offers
version: 1.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  page_view_indicators: 1.3.1
  shared_preferences: 0.5.6
  progress_dialog: ^1.2.2
  #flutter_facebook_login: 3.0.0
  http: 0.12.1
  image_picker: ^0.6.5
  cached_network_image: ^2.1.0+1
  font_awesome_flutter: ^8.11.0
  share: ^0.6.5+4
  url_launcher:
  firebase_messaging: any
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  firebase_storage: ^3.1.5
  carousel_slider: ^2.3.1
  google_mobile_ads: ^0.11.0+2
  provider: ^5.0.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Almarai
      fonts:
        - asset: assets\fonts\Almarai-Bold.ttf
          weight: 700
        - asset: assets\fonts\Almarai-ExtraBold.ttf
          weight: 800
        - asset: assets\fonts\Almarai-Light.ttf
          weight: 300
        - asset: assets\fonts\Almarai-Regular.ttf